### PR TITLE
Other small modpacks changes

### PR DESCRIPTION
**Pull request by Jerome226**
Fix important bugs and changes some minor things. more advanced stuff will come later
there still a skin bug that need to be fixed, but apart of that everything seems to works

### CODE REVIEW

**Review by facetorched — CHANGES_REQUESTED** [review]
-In the past, disabling the forestry fluids caused NEI to crash when viewing related items. perhaps the GT version of NEI fixes this?

-Should telomerasecoremod be client only? from your description it sounded like it's client

-Last time I checked, the gravestone's mod did not take into account replaceble_blocks. Plus, some of those plants I wouldn't want to replace. Only the ones that are replaced when players try to place a block inside them. (I know which ones these are so if in fact replacable_blocks config does something, I will fill those in)

**Comment by Jerome226** [comment]
Not gonna lie, there currently other fluids related crash right now with the forestry still, the fluids hardly seems to be the only issue with them, I can also mark the telomerase core client only, also not sure about the gravestone config, I thought it worked but I can change it if it's not working.

**Comment by Jerome226** [comment]
The other crash seems to be due the the integration with the tfc+ water sac (the thing to drink water with), possible fix would be to disable forestry from autogenerating recipes from some items, that would likely fix the issues with the disabled fluids too, tho that would require to change some code by ourselves.

**Comment by facetorched** [comment]
This waterskin crash happens when you do what? click on the waterskin?

**Comment by Jerome226** [comment]
No, just looking through the still recipes does it for me

**Comment by facetorched** [comment]
Weird, version 1.19 of telomerase (the current version) did not have this issue

**Comment by Jerome226** [comment]
I will try to enable back the fluids I removed to see if it can fix it

**Comment by facetorched** [comment]
Confirm fluid crash fixed and gravestones actually ignore certain blocks. If so remove some plants

**Pull request merged**
